### ISSUE TITLE
Log the commit id of source being tagged

### ISSUE THREAD

**Issue by svicarioli** [LiquoriChris/azuredevops-extension-tag-git-release#2]
Minor request - It would be handy to log the commit id of the source that the tag is attached to (ie Build.SourceVersion).
Currently this task logs the commit of the tag itself.

Thanks for a very useful task!

**Comment by liquorichris** [comment]
I know this is over a year old, but I have updated the logging to show the actual commit id $(Build.SourceVersion). I also updated the project variable to have compatibility with yaml pipelines.
